name: hpdf
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=24.2=py311h06a4308_0
  - python=3.11.11=he870216_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - accelerate==1.5.2
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.5
      - bleach==6.2.0
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - comm==0.2.2
      - contourpy==1.3.1
      - cycler==0.12.1
      - datasets==3.4.1
      - debugpy==1.8.12
      - decorator==5.1.1
      - defusedxml==0.7.1
      - denoising-diffusion-pytorch==2.1.1
      - diffusers==0.32.2
      - dill==0.3.8
      - einops==0.8.1
      - ema-pytorch==0.7.7
      - et-xmlfile==2.0.0
      - executing==2.1.0
      - fastapi==0.115.11
      - fastjsonschema==2.21.2
      - ffmpy==0.5.0
      - filelock==3.18.0
      - fonttools==4.55.3
      - fqdn==1.5.1
      - freetype-py==2.5.1
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - gradio==5.22.0
      - gradio-client==1.8.0
      - groovy==0.1.2
      - grpcio==1.69.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.29.3
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.36.1
      - importlib-metadata==8.6.1
      - ipykernel==6.29.5
      - ipython==8.31.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - lark==1.2.2
      - lazy-loader==0.4
      - libigl==2.6.1
      - lightning-utilities==0.12.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mediapy==1.2.2
      - mistune==3.1.4
      - multidict==6.2.0
      - multiprocess==0.70.16
      - natsort==8.4.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - notebook-shim==0.2.4
      - numpy==2.2.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - openpyxl==3.1.5
      - orjson==3.10.15
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - patsy==1.0.1
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.6
      - pooch==1.8.2
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.48
      - propcache==0.3.0
      - protobuf==5.29.3
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==19.0.1
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pyglet==2.1.2
      - pygments==2.19.1
      - pyopengl==3.1.0
      - pyparsing==3.2.1
      - pyrender==0.1.45
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pytorch-fid==0.3.0
      - pytz==2025.1
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==13.9.4
      - rpds-py==0.27.1
      - ruff==0.11.2
      - safehttpx==0.1.6
      - safetensors==0.5.3
      - scikit-image==0.25.0
      - scikit-learn==1.6.1
      - scipy==1.16.0
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - stack-data==0.6.3
      - starlette==0.46.1
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tifffile==2025.1.10
      - tinycss2==1.4.0
      - tokenizers==0.21.1
      - tomlkit==0.13.2
      - --extra-index-url https://download.pytorch.org/whl/cu126
      - torch==2.6.0+cu126
      - torch-fidelity==0.3.0
      - torchaudio==2.6.0+cu126
      - torchmetrics==1.6.1
      - torchvision==0.21.0+cu126
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.50.0
      - trimesh==4.5.3
      - triton==3.2.0
      - typer==0.15.2
      - types-python-dateutil==2.9.0.20250822
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - uri-template==1.3.0
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - xxhash==3.5.0
      - yarl==1.18.3
      - zipp==3.21.0
